# Generated by Django 5.2.7 on 2025-10-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
            ],
            options={
                'verbose_name_plural': 'Empresa',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'parametros_sistema',
            },
        ),
    ]
